#!/bin/sh
# Starts the platform's core with the fake model and checks it answers the way
# the interface uses it: health, one AG-UI run to its end, the process
# catalogue, the page with its security headers. Then takes it all down.
#
#   tools/smoke.sh [env-file]     # default: generated by tools/ci-env.sh
#
# Voice and the scraper stay off: their images carry speech models and a
# browser, and nothing in the core waits for them. Everything runs under its
# own project and its own volume, so it never touches a stack of yours.
set -eu

here=$(cd "$(dirname "$0")" && pwd)
cd "${here}/.."

project="agent-platform-smoke"
env_file="${1:-}"
if [ -z "${env_file}" ]; then
  env_file=$(mktemp)
  "${here}/ci-env.sh" > "${env_file}"
fi

compose() {
  POSTGRES_VOLUME="${project}_postgres-data" \
    docker compose --project-name "${project}" --env-file "${env_file}" "$@"
}

cleanup() {
  status=$?
  if [ "${status}" -ne 0 ]; then
    echo "--- smoke test failed: the logs of the core ---"
    compose logs --no-color --tail 80 master-agent process-service memory-service frontend || true
  fi
  compose down --volumes --remove-orphans > /dev/null 2>&1 || true
  exit "${status}"
}
trap cleanup EXIT

step() { printf '\n== %s\n' "$*"; }

step "starting the core (fake model)"
compose up --build --detach --wait --wait-timeout 300 master-agent process-service frontend

step "master agent: ready, and its dependencies with it"
curl --fail --silent --show-error http://127.0.0.1:8000/health/ready
echo

step "master agent: the transparency report"
curl --fail --silent --show-error http://127.0.0.1:8000/transparency | head -c 400
echo

step "master agent: one AG-UI run, to its end"
run=$(curl --fail --silent --show-error --no-buffer --max-time 60 \
  -X POST http://127.0.0.1:8000/agui \
  -H 'Content-Type: application/json' -H 'Accept: text/event-stream' \
  -d '{"threadId":"smoke","runId":"smoke-1","state":{},"messages":[{"id":"m1","role":"user","content":"hello"}],"tools":[],"context":[],"forwardedProps":{}}')
echo "${run}" | grep -q '"type":"TEXT_MESSAGE_CONTENT"' || { echo "no text in the run"; exit 1; }
echo "${run}" | grep -q '"type":"RUN_FINISHED"' || { echo "the run did not finish"; exit 1; }
echo "streamed $(echo "${run}" | grep -c '^data:') events, ending in RUN_FINISHED"

step "process service: ready, with its catalogue"
curl --fail --silent --show-error http://127.0.0.1:8300/health/ready
echo
curl --fail --silent --show-error http://127.0.0.1:8300/processes | grep -q '"example-approval"'
echo "catalogue lists example-approval"

step "frontend: the page, with its security headers"
headers=$(curl --fail --silent --show-error --dump-header - --output /dev/null http://127.0.0.1:3000/)
echo "${headers}" | grep -qi '^content-security-policy:.*nonce-' || { echo "no CSP with a nonce"; exit 1; }
echo "${headers}" | grep -qi '^x-content-type-options: nosniff' || { echo "no nosniff"; exit 1; }
echo "page served with its Content Security Policy"

step "smoke test passed"
